[package]
name = "stationeers-mips-unittest"
version = "0.1.0"
authors = ["Robert Forsman <git@thoth.purplefrog.com>"]
edition = "2018"

[dependencies]
"rand" = "0.7.3"

[lib]
name="stationeers_mips_unittest"
crate-type = ["dylib"]
path = "src/lib.rs"
